### ISSUE TITLE
Not working with conda-build!=1.18.2

### ISSUE THREAD

**Issue by bjlittle** [SciTools-incubator/centrally-managed-conda#3]
A tale of woe ...

Require to update `centrally-managed-conda` to work with more recent versions:

For example, using `conda-build-2.0.6-py27_0`, you have to set `CONDA_NPY`, but then the following exception is raised:
```python
TASK: Update source cache
Traceback (most recent call last):
  File "/var/tmp/itwl/conda_cray/tmp_envs/a8662ca63208c6513172/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/var/tmp/itwl/conda_cray/tmp_envs/a8662ca63208c6513172/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/tmp/itwl/conda_cray/tmp_envs/a8662ca63208c6513172/lib/python2.7/site-packages/centrally_managed_conda/fetch_sources.py", line 8, in <module>
    from conda_build import external
ImportError: cannot import name external
CalledProcessError: Command '['bash', '/home/h05/itwl/projects/git/configuration/cray/conda_build/update_channel.sh']' returned non-zero exit status 1
```

The `conda-build` API has moved on ... i.e. in `fetch_sources.py` replace `from conda_build import external` with `import conda_build.os_utils.external as external` and the function `execute` no longer exists in `conda_build.utils` ... there may be more issues to unravel here.
